#ifndef _PROJECT_PUNCHER_TEXT_EN_US_
#define _PROJECT_PUNCHER_TEXT_EN_US_

const PROGMEM char* enUS[] = {
    "Proj.Holepuncher",
    "Notice",
    "Warning",
    "Error",
    "Next",
    "Back",
    "Progress",
    "Remaining",
    "Duration",
    "Menu",
    "About",
    "Proj.Holepuncer",
    "@mr258876",
    "version",
    "DEV20220700",
    "Settings",
    "Language",
    "X axis",
    "Y axis",
    "Z axis",
    "Perimeter",
    "Speed",
    "V. Endstop",
    "Es. Thres.",
    "Current",
    "Encoder",
    "Reverse Enc.",
    "encoder now disable.",
    "Magnet not detected,",
    "No encoder, ",
    "Calibrating encoder",
    "Calibrate enc.",
    "Please wait...",
    "Reset All",
    "Reset all settings?",
    "",
    "Is reseted",
    "Wireless"
};

#endif
