#ifndef _PROJECT_PUNCHER_TEXT_EN_US_
#define _PROJECT_PUNCHER_TEXT_EN_US_

const PROGMEM char* enUS[] = {
    "Proj.Holepuncher",
    "Notice",
    "Warning",
    "Error",
    "Next",
    "Back",
    "Progress",
    "Remaining",
    "Duration",
    "Menu",
    "About",
    "Proj.Holepuncer",
    "@mr258876",
    "version",
    "DEV20220715",
    "Settings",
    "Language",
    "X axis",
    "Y axis",
    "Z axis",
    "Length",
    "Speed",
    "V. Endstop",
    "Es. Thres.",
    "Current",
    "Encoder",
    "Reverse Enc.",
    "encoder now disable.",
    "Magnet not detected,",
    "Communication fail,",
    "Calibrating encoder",
    "Calibrate enc.",
    "Please wait...",
    "Reset All",
    "Reset all settings?",
    "",
    "Is reseted",
    "Wifi",
    "Connect",
    "Conn To",
    "SSID",
    "Pwd.",
    "IP",
    "All Networks",
    "Status",
    "Connected",
    "No conn.",
    "Could not connect",
    "to your wifi.",
    "Connecting...",
    "Auto Connect",
    "Zeroing...",
    "Zreoing Failed.",
    "Check Settings.",
    "Encoder Disabled.",
    "Puncher Busy.",
    "Diam. Ratio",
    "Connecting Encoder",
    "Length Type",
    "Feed Paper",
    "Return Paper",
    "Feed"
};

#endif
