// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Project_Puncher

#include "../ui.h"

void ui_Feed_Screen_screen_init(void)
{
    ui_Feed_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Feed_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Feed_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Feed_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Feed_Title_Panel = lv_obj_create(ui_Feed_Screen);
    lv_obj_set_width(ui_Feed_Title_Panel, 128);
    lv_obj_set_height(ui_Feed_Title_Panel, 16);
    lv_obj_set_align(ui_Feed_Title_Panel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Feed_Title_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Feed_Title_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Feed_Title_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Feed_Title_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Feed_Title_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Feed_Title_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Feed_Title_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Feed_title = lv_label_create(ui_Feed_Title_Panel);
    lv_obj_set_width(ui_Feed_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Feed_title, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Feed_title, _("Feed"));
    lv_obj_set_style_text_color(ui_Feed_title, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Feed_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Feed_Roller = lv_roller_create(ui_Feed_Screen);
    lv_roller_set_options(ui_Feed_Roller, _("_feed_roller_options"), LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_Feed_Roller, 4, LV_ANIM_OFF);
    lv_obj_set_width(ui_Feed_Roller, 128);
    lv_obj_set_height(ui_Feed_Roller, 48);
    lv_obj_set_x(ui_Feed_Roller, 0);
    lv_obj_set_y(ui_Feed_Roller, 16);
    lv_obj_set_style_text_color(ui_Feed_Roller, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Feed_Roller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Feed_Roller, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Feed_Roller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Feed_Roller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Feed_Roller, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Feed_Roller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Feed_Roller, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Feed_Roller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Feed_Roller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Feed_Roller, ui_event_Feed_Roller, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Feed_Screen, ui_event_Feed_Screen, LV_EVENT_ALL, NULL);

}
