// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Project_Puncher_NG

#include "../ui.h"

void ui_FeedScreen_screen_init(void)
{
    ui_FeedScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FeedScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_flex_flow(ui_FeedScreen, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_FeedScreen, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_FeedScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_FeedScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_FeedScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_FeedScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_FeedScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_FeedScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FeedTopBar = lv_obj_create(ui_FeedScreen);
    lv_obj_set_width(ui_FeedTopBar, lv_pct(100));
    lv_obj_set_height(ui_FeedTopBar, lv_pct(20));
    lv_obj_set_align(ui_FeedTopBar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FeedTopBar, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_FeedTopBar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FeedTopBar, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_FeedTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_FeedTopBar, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_FeedTopBar, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_FeedTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_FeedTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FeedBackButton = lv_btn_create(ui_FeedTopBar);
    lv_obj_set_height(ui_FeedBackButton, 25);
    lv_obj_set_width(ui_FeedBackButton, lv_pct(15));
    lv_obj_set_x(ui_FeedBackButton, 30);
    lv_obj_set_y(ui_FeedBackButton, -22);
    lv_obj_set_align(ui_FeedBackButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_FeedBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_FeedBackButton, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_FeedBackButton, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FeedBackButtonLabel = lv_label_create(ui_FeedBackButton);
    lv_obj_set_width(ui_FeedBackButtonLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_FeedBackButtonLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_FeedBackButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FeedBackButtonLabel, LV_SYMBOL_LEFT);

    ui_FeedTitle = lv_label_create(ui_FeedTopBar);
    lv_obj_set_width(ui_FeedTitle, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_FeedTitle, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_FeedTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FeedTitle, _("Feed"));
    lv_obj_set_style_text_font(ui_FeedTitle, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FeedPanel = lv_obj_create(ui_FeedScreen);
    lv_obj_set_width(ui_FeedPanel, lv_pct(100));
    lv_obj_set_height(ui_FeedPanel, lv_pct(80));
    lv_obj_set_align(ui_FeedPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FeedPanel, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_FeedPanel, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_FeedPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_FeedStopButton = lv_btn_create(ui_FeedPanel);
    lv_obj_set_width(ui_FeedStopButton, 75);
    lv_obj_set_height(ui_FeedStopButton, 75);
    lv_obj_set_align(ui_FeedStopButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FeedStopButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_FeedStopButton, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_FeedStopButton, lv_color_hex(0xD20A0A), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_FeedStopButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FeedStopButtonLabel = lv_label_create(ui_FeedStopButton);
    lv_obj_set_width(ui_FeedStopButtonLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_FeedStopButtonLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_FeedStopButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FeedStopButtonLabel, _("STOP"));

    ui_FeedSpeedPanel = lv_obj_create(ui_FeedPanel);
    lv_obj_set_width(ui_FeedSpeedPanel, lv_pct(50));
    lv_obj_set_height(ui_FeedSpeedPanel, lv_pct(100));
    lv_obj_set_align(ui_FeedSpeedPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FeedSpeedPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_FeedSpeedPanel, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_FeedSpeedPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_FeedSpeedPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_FeedSpeedPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_FeedSpeedPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_FeedSpeedPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_FeedSpeedPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_FeedSpeedPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FeedPlusButton = lv_btn_create(ui_FeedSpeedPanel);
    lv_obj_set_width(ui_FeedPlusButton, 75);
    lv_obj_set_height(ui_FeedPlusButton, 30);
    lv_obj_set_align(ui_FeedPlusButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FeedPlusButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_FeedPlusButton, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_FeedPlusButtonLabel = lv_label_create(ui_FeedPlusButton);
    lv_obj_set_width(ui_FeedPlusButtonLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_FeedPlusButtonLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_FeedPlusButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FeedPlusButtonLabel, LV_SYMBOL_UP);
    lv_obj_set_style_text_font(ui_FeedPlusButtonLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FeedRoller = lv_roller_create(ui_FeedSpeedPanel);
    lv_roller_set_options(ui_FeedRoller, "+4\n+3\n+2\n+1\n0\n-1\n-2\n-3\n-4", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_FeedRoller, 75);
    lv_obj_set_height(ui_FeedRoller, 75);
    lv_obj_set_align(ui_FeedRoller, LV_ALIGN_CENTER);

    ui_FeedMinusButton = lv_btn_create(ui_FeedSpeedPanel);
    lv_obj_set_width(ui_FeedMinusButton, 75);
    lv_obj_set_height(ui_FeedMinusButton, 30);
    lv_obj_set_align(ui_FeedMinusButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FeedMinusButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_FeedMinusButton, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_FeedMinusButtonLabel = lv_label_create(ui_FeedMinusButton);
    lv_obj_set_width(ui_FeedMinusButtonLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_FeedMinusButtonLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_FeedMinusButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FeedMinusButtonLabel, LV_SYMBOL_DOWN);
    lv_obj_set_style_text_font(ui_FeedMinusButtonLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_FeedBackButton, ui_event_FeedBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FeedStopButton, ui_event_FeedStopButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FeedPlusButton, ui_event_FeedPlusButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FeedMinusButton, ui_event_FeedMinusButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FeedScreen, ui_event_FeedScreen, LV_EVENT_ALL, NULL);
}
