// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Project_Puncher

#include "../ui.h"

void ui_Home_Screen_screen_init(void)
{
    ui_Home_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Title_Panel = lv_obj_create(ui_Home_Screen);
    lv_obj_set_width(ui_Home_Title_Panel, 128);
    lv_obj_set_height(ui_Home_Title_Panel, 16);
    lv_obj_set_align(ui_Home_Title_Panel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Home_Title_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Title_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Title_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Home_Title_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Home_Title_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Home_Title_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Home_Title_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Title = lv_label_create(ui_Home_Title_Panel);
    lv_obj_set_width(ui_Home_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_Title, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Home_Title, _("Home"));
    lv_obj_set_style_text_color(ui_Home_Title, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Home_Title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Status_Icons = lv_label_create(ui_Home_Title_Panel);
    lv_obj_set_width(ui_Status_Icons, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Status_Icons, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Status_Icons, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_text_color(ui_Status_Icons, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Status_Icons, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Content_Panel = lv_obj_create(ui_Home_Screen);
    lv_obj_set_width(ui_Home_Content_Panel, 64);
    lv_obj_set_height(ui_Home_Content_Panel, 48);
    lv_obj_set_x(ui_Home_Content_Panel, 0);
    lv_obj_set_y(ui_Home_Content_Panel, 16);
    lv_obj_set_flex_flow(ui_Home_Content_Panel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Home_Content_Panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Home_Content_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Content_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Content_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Home_Content_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Home_Content_Panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Home_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Home_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Status = lv_label_create(ui_Home_Content_Panel);
    lv_obj_set_width(ui_Home_Status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_Status, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Home_Status, "In Idle");
    lv_obj_set_style_text_color(ui_Home_Status, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Home_Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_ETA = lv_label_create(ui_Home_Content_Panel);
    lv_obj_set_width(ui_Home_ETA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_ETA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Home_ETA, 0);
    lv_obj_set_y(ui_Home_ETA, 16);
    lv_label_set_text(ui_Home_ETA, _("ETA"));
    lv_obj_set_style_text_color(ui_Home_ETA, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Home_ETA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_ETA_Value = lv_label_create(ui_Home_Content_Panel);
    lv_obj_set_width(ui_Home_ETA_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_ETA_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Home_ETA_Value, 0);
    lv_obj_set_y(ui_Home_ETA_Value, 32);
    lv_label_set_text(ui_Home_ETA_Value, "8:88:88");
    lv_obj_set_style_text_color(ui_Home_ETA_Value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Home_ETA_Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Button_Panel = lv_obj_create(ui_Home_Screen);
    lv_obj_set_width(ui_Home_Button_Panel, 64);
    lv_obj_set_height(ui_Home_Button_Panel, 48);
    lv_obj_set_x(ui_Home_Button_Panel, 64);
    lv_obj_set_y(ui_Home_Button_Panel, 16);
    lv_obj_set_flex_flow(ui_Home_Button_Panel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Home_Button_Panel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Home_Button_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Button_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Button_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Home_Button_Panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Home_Button_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Home_Button_Panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Home_Button_Panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Button1 = lv_btn_create(ui_Home_Button_Panel);
    lv_obj_set_width(ui_Home_Button1, 58);
    lv_obj_set_height(ui_Home_Button1, 22);
    lv_obj_set_align(ui_Home_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Home_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Home_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Home_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Home_Button1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Home_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Home_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Home_Button1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Home_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Home_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Home_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Home_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Home_Button1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Home_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Home_Button1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Home_Button1_Label = lv_label_create(ui_Home_Button1);
    lv_obj_set_width(ui_Home_Button1_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_Button1_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Home_Button1_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Home_Button1_Label, _("Feed"));

    ui_Home_Button2 = lv_btn_create(ui_Home_Button_Panel);
    lv_obj_set_width(ui_Home_Button2, 58);
    lv_obj_set_height(ui_Home_Button2, 22);
    lv_obj_set_align(ui_Home_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Home_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Home_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Home_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Home_Button2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Home_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Home_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Home_Button2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Home_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Home_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Home_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Home_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Home_Button2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Home_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Home_Button2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Home_Button2_Label = lv_label_create(ui_Home_Button2);
    lv_obj_set_width(ui_Home_Button2_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_Button2_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Home_Button2_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Home_Button2_Label, _("Setting"));

}
