// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Project_Puncher

#include "../ui.h"

void ui_Info_Screen_screen_init(void)
{
    ui_Info_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Info_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Info_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Title_Panel = lv_obj_create(ui_Info_Screen);
    lv_obj_set_width(ui_Info_Title_Panel, 128);
    lv_obj_set_height(ui_Info_Title_Panel, 16);
    lv_obj_set_align(ui_Info_Title_Panel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Info_Title_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Info_Title_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Title_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Info_Title_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Info_Title_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Info_Title_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Info_Title_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_title = lv_label_create(ui_Info_Title_Panel);
    lv_obj_set_width(ui_Info_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_title, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Info_title, _("Info"));
    lv_obj_set_style_text_color(ui_Info_title, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Content_Panel = lv_obj_create(ui_Info_Screen);
    lv_obj_set_width(ui_Info_Content_Panel, 128);
    lv_obj_set_height(ui_Info_Content_Panel, 32);
    lv_obj_set_x(ui_Info_Content_Panel, 0);
    lv_obj_set_y(ui_Info_Content_Panel, 16);
    lv_obj_set_flex_flow(ui_Info_Content_Panel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Info_Content_Panel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Info_Content_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Info_Content_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Content_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Info_Content_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Info_Content_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Info_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Info_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Text_Label = lv_label_create(ui_Info_Content_Panel);
    lv_obj_set_width(ui_Info_Text_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Text_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Info_Text_Label, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Info_Text_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info_Text_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Button_Panel = lv_obj_create(ui_Info_Screen);
    lv_obj_set_width(ui_Info_Button_Panel, 128);
    lv_obj_set_height(ui_Info_Button_Panel, 16);
    lv_obj_set_align(ui_Info_Button_Panel, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Info_Button_Panel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Info_Button_Panel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Info_Button_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Info_Button_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Button_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Info_Button_Panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Info_Button_Panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Info_Button_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Info_Button_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Button1 = lv_btn_create(ui_Info_Button_Panel);
    lv_obj_set_width(ui_Info_Button1, 59);
    lv_obj_set_height(ui_Info_Button1, 14);
    lv_obj_set_align(ui_Info_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Info_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Info_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Info_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Info_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Info_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Info_Button1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Info_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Info_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Info_Button1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Info_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Info_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Info_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Info_Button1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Info_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Info_Button1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Info_Button1_Label = lv_label_create(ui_Info_Button1);
    lv_obj_set_width(ui_Info_Button1_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Button1_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Info_Button1_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Info_Button1_Label, _("Back"));

    ui_Info_Button2 = lv_btn_create(ui_Info_Button_Panel);
    lv_obj_set_width(ui_Info_Button2, 59);
    lv_obj_set_height(ui_Info_Button2, 14);
    lv_obj_set_align(ui_Info_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Info_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Info_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Info_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Info_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Info_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Info_Button2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Info_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Info_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Info_Button2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Info_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Info_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Info_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Info_Button2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Info_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Info_Button2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Info_Button2_Label = lv_label_create(ui_Info_Button2);
    lv_obj_set_width(ui_Info_Button2_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Button2_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Info_Button2_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Info_Button2_Label, _("OK"));

}
