// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Project_Puncher

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

void ui_event_Home_Button1_onClick(lv_event_t * e);
void ui_event_Home_Button2_onClick(lv_event_t * e);
void ui_event_Info_Button1_onClick(lv_event_t * e);
void ui_event_Info_Button2_onClick(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
